### PR TITLE
add README

### PR DESCRIPTION
**Pull request by trdthg**
Signed-off-by: trdthg <trdthg@outlook.com>
运行方法都不教 😡

### CODE REVIEW

**Review by xhebox — DISMISSED** [review]

**Comment by xhebox** [comment]
@trdthg 

> The base branch requires all commits to be signed

**Comment by trdthg** [comment]
去了

**Comment by xhebox** [comment]
> 去了

不可 建议commit -s -a --amend, push -f

**Comment by trdthg** [comment]
😅

**Review by xhebox — APPROVED** [review]

**Pull request merged**
